# Generated by Django 4.2 on 2024-09-05 15:20

import core.file_system
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plugins.adverts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0066_issue_type_bleach_20240507_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Text to identify this advert.', max_length=255)),
                ('image', models.ImageField(storage=core.file_system.JanewayFileSystemStorage(), upload_to=plugins.adverts.models.advert_images_upload_path)),
                ('start_display', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_display', models.DateTimeField(blank=True, help_text='Leave blank to always display this advert.', null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
